services:

  front:
    build: ./client
    restart: unless-stopped
    ports:
      - 3000:3000  
    volumes:
      - ./client:/webapp

  back:
    build: ./server
    restart: unless-stopped
    ports:
      - 3310:3310  
    depends_on:
      - db
    volumes:
      - ./server:/app
    environment:
      THEGOODCORNER_DBPASS: ${DBPASS}

  db:
    image: postgres:16
    restart: unless-stopped

    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      THEGOODCORNER_DBPASS_ADMIN: ${DBPASS_ADMIN}
    ports:
      - 5432:5432  
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
