# //Use "REST Client" and SQLite Extensions for this file.

// Get ALL categories
POST http://localhost:3010/
Content-Type: application/json

{
    "query": "query QueryAllCategories { getAllCategories { id name } }"
}

