//Use "REST Client" and SQLite Extensions for this file.

GET http://localhost:3010/movies/count
Content-Type: text/plain

###

GET http://localhost:3010/movies/totalBudget
Content-Type: text/plain

###

GET http://localhost:3010/movies

###

GET http://localhost:3010/movies?minYear=2008
Content-Type: text/plain

###

GET http://localhost:3010/movies?reqTime=11:00,16:00
Content-Type: text/plain

###

GET http://localhost:3010/movies?minYear=2008&reqTime=11:00,16:00
Content-Type: text/plain

###

POST http://localhost:3010/movies
Content-Type: application/json

{
    "Titre": "Le reve d'un poulet",
    "Année": 1989,
    "Prix": 49,
    "Horaires":["16:00","21:00"]
}

###

PUT http://localhost:3010/movies/181
Content-Type: application/json

{
    "Titre": "Un coup, quatre trous",
    "Année": 2013,
    "Prix": 29,
    "Horaires":["17:00","22:00"]
}


###
// Ajout de ',' pour supprimer plusieurs elements .
DELETE  http://localhost:3010/movies/188,189
