// Get ALL Tags
POST http://localhost:3010/
Content-Type: application/json

{
    "query": "query QueryAllTags { getAllTags { id name } }"
}

###
// Get tags with id
POST http://localhost:3010/
Content-Type: application/json

{
    "query": "query ExampleQuery($getTagById: Float!) { getTagById(id: $getTagById) { id name }}",
    "variables": {
    "getTagById": 235
  }
}
